name: i18n
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  yaml: ^3.1.4
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/i18n/en_US.yaml
    - lib/assets/i18n/es_ES.yaml
    - lib/assets/i18n/pt_BR.yaml